### ISSUE TITLE
Set this up like Wicklowcam.com using the demo-cam from Rosslare.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/remembrancecam#1]
See this: https://github.com/evercam/wicklowcam

which uses Github pages to publish as this: www.wicklowcam.com

Clever eh ?

M

**Comment by muneeb2542** [comment]
i am looking into it hopefully will have a solutin as soon as possible

**Comment by marcoherbst** [comment]
@muneeb2542  you might want to look again, the image does not seem to be playing like on wicklowcam

**Comment by muneeb2542** [comment]
yes i'm looking into it right now.

**Comment by muneeb2542** [comment]
The dns were the previous ones for the azure site.So i just fixed that.

**Comment by muneeb2542** [comment]
you should just clear your browser cache and then remembrancecam.com will automatically redirect to www.remembrancecam.com

**Comment by marcoherbst** [comment]
Nice one.
